// const TRANSLATIONS = {
//   en: {
//     alertMessage: "Please Enter Correct Information",
//     continue: "Continue",
//     register: "Register",
//   },
//   mr: {
//     alertMessage: "कृपया योग्य माहिती भरा",
//     continue: "सुरू ठेवा",
//     register: "नोंदणी करा",
//   },
// };

// export default TRANSLATIONS;

// Onboarding Screen

const TRANSLATIONS = {
  en: {
    alertMessage: "Please Enter Correct Information",
    continue: "Continue",
    register: "Register",
    password: "Password",
    login: "Login",

    enterMobileNumber: "Please Enter Mobile Number",
    enterName: "Please Enter Name",
    enterPassword: "Please Enter Password",
    invalidPassword: "Please enter a valid password with at least 8 characters",

    home: "Home",
    profile: "Profile",
    findPeople: "Find People",
    notifications: "Notifications",
    settings: "Settings",
    meetingCalender: "Meeting Calender",
    bookmarkItem: "Bookmark",
    createBiodata: "Create Biodata",
    chooseBiodataDesign: "Choose Biodata Design",
    signUp: "Sign Up",
    explore: "Explore",
    welcome: "Welcome 🙏",
    profileCreatedListHeadingHomePage: "Created Profile`s",
    verifiedTextHomePage: "Verified",
    name: "Name",
    age: "Age",
    occupation: "Occupation",
    location: "Location",
    firstName: "First Name",
    middleName: "Father Name",
    surname: "Surname",
    qualification: "Qualification",
    noAlbumWarning: "Album Not Available",
    album: "Album",
    albumPrivateText: "This album is private",
    requestAlbumPermission: "Request Album Permission",
    personalInfoPrivateText: "Personal Information is Private",
    requestForPersonalInformation: "Request to Unlock Personal Information",
    familyInfoPrivateText: "Family Information is Private",
    requestForfamilyInformation: "Request to Unlock Family Information",
    homeAddressInfoPrivateText: "Home Address is Private",
    requestForHomeAddress: "Request to Unlock Home Address",
    direction: "Direction",
    mobileNumberInfoPrivateText: "Contact Number is Private",
    requestForMobileNumber: "Request to Unlock Mobile Number",
    contact: "Contact",
    private: "Private",
    sendIntrest: "Show Intrest",
    call: "Call",
    viewProfile: "View Profile",
    goBack: "Previous",
    goNext: "Next",
    // Onboarding Screen
    imCandidate: "Im candidate",
    imKolidut: "Im Kolidut",

    imRelativeOfCandidate: "Im relative of candidate",
    tellUsAboutYourSelf: "Tell us about Yourself",
    tellusSubText: "Please select option which describe about yourself",
    selectRelation: "Choose your relation",
    selectOption: "Choose Option from below",

    selectRelationSubText:
      "Please select option which describe your relationship with candidiate",
    selectOptionSubText:
      "Please select the option that describes yourself as a candidate",

    father: "Father",
    mother: "Mother",
    other: "Other",
    male: "Male",
    female: "Female",
    mobileNumber: "Mobile Number",
    mobileNumberSubText: "Please enter your contact detail",

    //Side Drawer
    timeline: "My Timeline",

    //BioData
    feet: "Feet",
    inch: "Inch",
    candidateTypeMale: "Bride",
    candidateTypeFemale: "Groom",
    expectationSectionTitle: "Expectations from the bride/ groom",
    biodataTitle: "Create Biodata",
    submit: "Submit",
    basicDetailTitle: "Basic Details",
    candidateType: "Candidate Type:",
    selectCandidateTypePlaceHolder: "Select Candidate Type",
    nameTitle: "Name :",
    namePlaceholder: "Enter your name",
    middleNameTitle: "Middle Name:",
    middleNamePlaceHolder: "Enter middle name here",
    surnameTitle: "Surname:",
    surnamePlaceHolder: "Enter surname here",
    fullNameTitle: "Full Name:",
    dob: "Date of Birth:",
    ageTitle: "Age:",
    maritalStatusTitle: "Marital Status:",
    maritalStatusPlaceholder: "Choose marital status",
    complexion: "Complexion:",
    complexionPlaceholder: "Choose complexion",
    single: "Single",
    married: "Married",
    divorced: "Divorced",
    widowed: "Widowed",
    //Complexion Dropdown
    very_fair: "Very Fair",
    fair: "Fair",
    light: "Light Fair",
    medium: "Medium Fair",
    olive: "Olive",
    tan: "Tan",
    brown: "Brown",
    dark: "Dark",
    //album section
    addImageTitle: "Add Image",
    profilePicture: "Profile Picture",
    useAsProfilePicture: "Set as Profile Pic",
    albumGuideText:
      "You can choose another photo as profile pic by clicking button in blue",
    personalInfoHeading: "Personal Info",
    casteTitle: "Caste :",
    castPlaceHolder: "Choose your caste",
    bloodGroupTitle: "Blood Group :",
    bloodGroupPlaceHolder: "Choose blood group",
    physicalDisabledTitle: "Physical Disablity :",
    physicalDisablePlaceholder: "Are you physically disabled ?",
    heightTitle: "Height :",
    feetPlaceholder: "Feet",
    inchPlaceholder: "Inch",
    birthPlaceTitle: "Birth Place :",
    birthTimeTitle: "Birth Time :",
    timePlaceholder: "Time",
    hourPlaceholder: "Hour",
    minutePlaceholder: "Minute",
    qualificationTitle: "Qualification :",
    qualificationPlaceholder: "Choose your qualification",
    occupationTitle: "Occupation :",
    occupationPlaceholder: "Choose your occupation",
    occupationMoreInfoTitle: "Occupation more info :",
    occupationMoreinfoPlaceholder: "Enter more info",
    yearlyincomeTitle: "Yearly Income :",
    yearlyincomePlaceholder: "Choose your income range",
    candidateWorkPlaceTitle: "Work Place :",
    familyInfoTitle: "Family Info",
    fatherNameTitle: "Father`s Full Name :",
    fatherNamePlaceholder: "Enter father name",
    fatherOccupationTitle: "Father`s Occupation",
    fatherOccupationPlaceholder: "Enter father`s occupation",
    motherNameTitle: "Mother`s Full Name :",
    motherNamePlaceholder: "Enter mother Name",
    totalBrotherTitle: "Total Brother`s",
    totalSisterTitle: "Total Sister`s",
    totalMarriedBrotherTitle: "Total Married Brother`s",
    totalMarriedSisterTitle: "Total Married Sister`s",
    maternalUncleTitle: "Maternal Uncle Full Name :",
    maternalUnclePlaceHolder: "firstname middlename surname",
    maternalUnclePlace: "Maternal Uncle`s Place :",

    expectationsTitle: "Expectations :",
    expectationsPlaceholder: "choose 3 expections",
    expectationGuideText:
      "You can Leave it blank it don`t have any Expectation`s.",
    expectationAlertText: "You can select a maximum of 3 expectations.",
    expectationAlertTitle: "Limit reached",
    //LocationSection
    loacationInfoTitle: "Location Info",
    permanantAddresstitle: "Permanent Address :",
    //contactInfoSection
    contactInfoTitle: "Contact Info",
    emailTitle: "Email :",
    emailPlaceholder: "Enter email",
    candidateContactTitle: "Candidate Contact :",
    familyMemberContactTitle: "Family Member Contact",
    contactGuideInfoText:
      "Above Contact Number will be Provided as Contact on Biodata.",
    //occupation table
    Business: "Business",
    Unemployed: "Unemployed",
    Engineer: "Engineer",
    Doctor: "Doctor",
    Driver: "Driver",
    Teacher: "Teacher",
    Lawyer: "Lawyer",
    Nurse: "Nurse",
    Architect: "Architect",
    Electrician: "Electrician",
    Plumber: "Plumber",
    Carpenter: "Carpenter",
    Chef: "Chef",
    Pilot: "Pilot",
    Artist: "Artist",
    Farmer: "Farmer",
    Mechanic: "Mechanic",
    Scientist: "Scientist",
    Pharmacist: "Pharmacist",
    SoftwareDeveloper: "Software Developer",
    Accountant: "Accountant",
    PoliceOfficer: "Police Officer",
    Other: "Other",
    //caste dropdown
    TokareKoli: "Tokare Koli",
    MahadevKoli: "Mahadev Koli",
    DhorKoli: "Dhor Koli",
    Koli: "Koli",
    // Other: "Other"
    tenth: "10th",
    twelvth: "12th",
    Engineering: "Engineering",
    BachelorDegree: "Bachelor's Degree",
    MasterDegree: "Master's Degree",
    PhD: "Ph.D.",
    Diploma: "Diploma",
    Certificate: "Certificate",
    AssociateDegree: "Associate Degree",
    VocationalTraining: "Vocational Training",
    ProfessionalQualification: "Professional Qualification",
    // Other: "Other"
    DontKnow: "Don`t Know",
    Yes: "Yes",
    No: "No",
    District: "District",
    Subdistrict: "Subdistrict",
    Village: "Village",
    Maharashtra: "Maharashtra",
    Search: "Search...",
    timeOfDayMorningEnglish: "Morning",
    timeOfDayAfternoonEnglish: "Afternoon",
    timeOfDayEveningEnglish: "Evening",
    timeOfDayNightEnglish: "Night",
    //actual bioata pic
    overview: "Overview",
    vaivahikStiti: "Marital Status",
    vyavsay: "Occupation",
    raktgat: "Blood Group",
    gav: "Village",
    taluka: "Taluka",
    jilha: "District",
    mamacheGav: "Maternal Uncle's Village",
    apangatva: "Disability",
    janmakundaliMahiti: "Horoscope Information",
    janmasthan: "Birthplace",
    biodata: "Biodata",
    vaiyaktikMahiti: "Personal Information",
    sampurnaNav: "Full Name",
    janmatarih: "Date of Birth",
    vay: "Age",
    varn: "Complexion",
    jat: "Caste",
    unchi: "Height",
    shaikshanikMahiti: "Educational Information",
    nokriVyavsay: "Job or Business",
    varshikUtpan: "Annual Income",
    nokricheThikan: "Job Location",
    kautumbikParshwabhumiTapsil: "Family Background Details",
    vadilNav: "Father's Name",
    vadilVyavsay: "Father's Occupation",
    aicheNav: "Mother's Name",
    ekunBhav: "Total Brothers",
    vivahitBhav: "Married Brothers",
    ekunBahin: "Total Sisters",
    vivahitBahin: "Married Sisters",
    mamacheSampurnaNav: "Maternal Uncle's Full Name",
    // mamacheGav: "Maternal Uncle's Village",
    samparkachiMahiti: "Contact Information",
    samparkKramank: "Contact Number",
    kaimchaPatta: "Permanent Address",
    apeksha: "Expectations",
    koniVisheshApekshaNahi: "No Special Expectations",
    adhikMahitiSathi: "For More Information",
    haIdMobileAppSearch:
      "Search this ID in the mobile app for more details and photos",
    janma: "Birth",
    //biodata template
    submitBtn: "Submit",
    noTemplateSelected: "No Template Selected",
    noImageAvailable: "No Image Available",
    chooseTemplate: "Choose Template",

    selectCandidateType: "Please Select Candidate Type.",
    // enterName: "Please Enter Name.",
    enterMiddleName: "Please Enter Middle Name.",
    enterSurname: "Please Enter Surname.",
    ageRequirement: "Candidate should be 18 Years Old.",
    chooseMaritalStatus: "Please choose marital status.",
    chooseComplexion: "Please choose valid complexion.",
    selectPhoto: "Please select Photo in album.",
    minimumPhotos: "Please select minimum 2 photos in album.",
    chooseCaste: "Please choose valid caste.",
    choosePhysicalStatus:
      "Please choose if the candidate is physically disabled.",
    chooseHeightFeet: "Please choose valid height in feet.",
    chooseHeightInch: "Please choose valid height in inches.",
    chooseBirthDistrict: "Please choose valid district.",
    chooseBirthSubDistrict: "Please choose valid Sub-District.",
    chooseBirthVillage: "Please choose valid village.",
    chooseBirthTime: "Please choose valid birth time or choose values again.",
    chooseQualification: "Please choose valid qualification.",
    chooseOccupation: "Please choose valid occupation.",
    chooseIncome: "Please choose valid yearly income range.",
    chooseWorkDistrict: "Please choose valid district.",
    chooseWorkSubDistrict: "Please choose valid Sub-District.",
    chooseWorkVillage: "Please choose valid village.",
    enterFatherName: "Please enter father name.",
    enterMotherName: "Please enter mother name.",
    enterMaternalUncleName: "Please enter maternal uncle name.",
    chooseMaternalDistrict: "Please choose valid district.",
    chooseMaternalSubDistrict: "Please choose valid Sub-District.",
    chooseMaternalVillage: "Please choose valid village.",
    chooseLocationDistrict: "Please choose valid district.",
    chooseLocationSubDistrict: "Please choose valid Sub-District.",
    chooseLocationVillage: "Please choose valid village.",
    enterCandidateMobile: "Please enter valid mobile number.",
    enterFamilyMobile: "Please enter valid mobile number.",
  },
  hi: {
    call: "संपर्क करें",
    alertMessage: "कृपया सही जानकारी दर्ज करें",
    continue: "जारी रखें",
    register: "पंजीकरण करें",
    password: "पासवर्ड",
    login: "लॉगिन",
    enterMobileNumber: "कृपया मोबाइल नंबर दर्ज करें",
    enterName: "कृपया नाम दर्ज करें",
    enterPassword: "कृपया पासवर्ड दर्ज करें",
    invalidPassword: "कृपया कम से कम 8 अक्षरों का एक मान्य पासवर्ड दर्ज करें",
    Unemployed: "बेरोजगार",
    Business: "व्यवसाय",

    home: "मुखपृष्ठ",
    profile: "प्रोफ़ाइल",
    findPeople: "लोगों को खोजें",
    notifications: "सूचनाएं",
    settings: "सेटिंग्स",
    meetingCalender: "बैठक कैलेंडर",
    bookmarkItem: "बुकमार्क",
    createBiodata: "बायोडाटा बनाएँ",
    chooseBiodataDesign: "बायोडाटा डिज़ाइन चुनें",
    signUp: "साइन अप करें",
    explore: "खोजें",
    welcome: "सुस्वागतम 🙏",
    profileCreatedListHeadingHomePage: "बनायें हुए बायोडाटा",
    verifiedTextHomePage: "सत्यापन",
    name: "नाम",
    age: "आयु",
    occupation: "पेशा",
    location: "स्थान",
    firstName: "मूल नाम",
    middleName: "पिता का नाम",
    surname: "कुलनाम",
    qualification: "योग्यता",
    noAlbumWarning: "एल्बम उपलब्ध नहीं है",
    album: "एल्बम",
    albumPrivateText: "यह एल्बम निजी है",
    requestAlbumPermission: "एल्बम देखने कि अनुमति ले",
    personalInfoPrivateText: "व्यक्तिगत जानकारी निजी है",
    requestForPersonalInformation: "व्यक्तिगत जानकारी देखने कि अनुमति ले",
    familyInfoPrivateText: "पारिवारिक जानकारी निजी है",
    requestForfamilyInformation: "पारिवारिक जानकारी देखने कि अनुमति ले",
    homeAddressInfoPrivateText: "घर का पता निजी है",
    requestForHomeAddress: "घर का पता देखने कि अनुमति ले",
    direction: "पता देखे",
    mobileNumberInfoPrivateText: "संपर्क नंबर निजी है",
    requestForMobileNumber: "मोबाइल नंबर देखने कि अनुमति ले",
    contact: "संपर्क करे ",
    private: "निजी",
    sendIntrest: "दिलचस्पी दिखाये",
    viewProfile: "प्रोफ़ाइल देखे",
    goBack: "पिछला पृष्ठ",
    goNext: "अगला पृष्ठ",
    // Onboarding Screen
    imCandidate: "मैं आवेदनकर्ता हूं",
    imKolidut: "में कोळीदूत हूं",
    imRelativeOfCandidate: "मैं आवेदनकर्ता का रिश्तेदार हूं",
    tellUsAboutYourSelf: "अपना परिचय दें",
    tellusSubText: "कृपया वह विकल्प चुनें जो आपके बारे में वर्णन करता हो",
    selectRelation: "अपना संबंध चुनें",
    selectRelationSubText:
      "कृपया विकल्प का चयन करें जो आवेदनकर्ता के साथ आपके संबंधों का वर्णन करता है",
    selectOptionSubText: "कृपया विकल्प चुनें",

    father: "पिता",
    mother: "माँ",
    other: "अन्य",
    male: "पुरुष",
    female: "महिला",
    mobileNumber: "मोबाइल नंबर",
    mobileNumberSubText: "कृपया अपना संपर्क विवरण दर्ज करें",
    selectOption: "नीचे से विकल्प चुनें",

    //Side Drawer
    timeline: "मेरी टाइमलाइन",

    //BioData
    feet: "फीट",
    inch: "इंच",
    candidateTypeMale: "वर",
    candidateTypeFemale: "वधू",
    expectationSectionTitle: "दूल्हा/दुल्हन से उम्मीदें",
    biodataTitle: "पर्ची बनाएँ",
    submit: "जमा करें",
    basicDetailTitle: "मूल विवरण",
    candidateType: "उम्मीदवार प्रकार:",
    selectCandidateTypePlaceHolder: "उम्मीदवार प्रकार चुनें",
    nameTitle: "नाम :",
    namePlaceholder: "अपना नाम दर्ज करें",
    middleNameTitle: "मध्य नाम:",
    middleNamePlaceHolder: "यहां मध्य नाम दर्ज करें",
    surnameTitle: "उपनाम:",
    surnamePlaceHolder: "यहां उपनाम दर्ज करें",
    fullNameTitle: "पूरा नाम:",
    dob: "जन्म तिथि:",
    ageTitle: "आयु:",
    maritalStatusTitle: "वैवाहिक स्थिति:",
    maritalStatusPlaceholder: "वैवाहिक स्थिति चुनें",
    complexion: "रंग:",
    complexionPlaceholder: "रंग चुनें",
    single: "अविवाहित",
    married: "विवाहित",
    divorced: "तलाकशुदा",
    widowed: "विधवा",
    //Complexion Dropdown
    very_fair: "बहुत गोरा",
    fair: "गोरा",
    light: "हल्का गोरा",
    medium: "मध्यम गोरा",
    olive: "जैतूनी",
    tan: "मध्यम भूरा",
    brown: "भूरा",
    dark: "काला",
    //album section
    addImageTitle: "चित्र जोड़ें",
    profilePicture: "प्रोफाइल चित्र",
    useAsProfilePicture: "प्रोफाइल चित्र सेट करें",
    albumGuideText:
      "- नीले बटन पर क्लिक करके आप दूसरी तस्वीर प्रोफाइल चित्र के रूप में चुन सकते हैं",
    personalInfoHeading: "व्यक्तिगत जानकारी",
    casteTitle: "जात :",
    castPlaceHolder: "अपनी जात चुनें",
    bloodGroupTitle: "रक्त समूह :",
    bloodGroupPlaceHolder: "रक्त समूह चुनें",
    physicalDisabledTitle: "शारीरिक विकलांगता :",
    physicalDisablePlaceholder: "क्या आप शारीरिक रूप से विकलांग हैं?",
    heightTitle: "ऊँचाई :",
    feetPlaceholder: "फुट",
    inchPlaceholder: "इंच",
    birthPlaceTitle: "जन्म स्थान :",
    birthTimeTitle: "जन्म समय :",
    timePlaceholder: "समय",
    hourPlaceholder: "घंटा",
    minutePlaceholder: "मिनट",
    qualificationTitle: "योग्यता :",
    qualificationPlaceholder: "अपनी योग्यता चुनें",
    occupationTitle: "व्यवसाय :",
    occupationPlaceholder: "अपना व्यवसाय चुनें",
    occupationMoreInfoTitle: "व्यवसाय की अधिक जानकारी :",
    occupationMoreinfoPlaceholder: "अधिक जानकारी डालें",
    yearlyincomeTitle: "वार्षिक आय :",
    yearlyincomePlaceholder: "अपनी आय सीमा चुनें",
    candidateWorkPlaceTitle: "कार्य स्थल :",
    familyInfoTitle: "परिवार की जानकारी",
    fatherNameTitle: "पिता का पूरा नाम :",
    fatherNamePlaceholder: "पिता का नाम दर्ज करें",
    fatherOccupationTitle: "पिता का व्यवसाय :",
    fatherOccupationPlaceholder: "पिता का व्यवसाय दर्ज करें",
    motherNameTitle: "मां का पूरा नाम :",
    motherNamePlaceholder: "मां का नाम दर्ज करें",
    totalBrotherTitle: "कुल भाई :",
    totalSisterTitle: "कुल बहनें :",
    totalMarriedBrotherTitle: "कुल विवाहित भाई :",
    totalMarriedSisterTitle: "कुल विवाहित बहनें :",
    maternalUncleTitle: "मामा का पूरा नाम :",
    maternalUnclePlaceHolder: "पहला नाम मध्य नाम उपनाम",
    maternalUnclePlace: "मामा का स्थान :",

    expectationsTitle: "अपेक्षाएँ :",
    expectationsPlaceholder: "३ अपेक्षाएँ चुनें",
    expectationGuideText:
      "यदि आपकी कोई अपेक्षाएँ नहीं हैं, तो इसे खाली छोड़ सकते हैं।",
    expectationAlertText: "आप अधिकतम ३ अपेक्षाएँ चुन सकते हैं।",
    expectationAlertTitle: "सीमा पूरी हुई",
    loacationInfoTitle: "स्थान की जानकारी",
    permanantAddresstitle: "स्थायी पता :",

    //contactInfoSection
    contactInfoTitle: "संपर्क जानकारी",
    emailTitle: "ईमेल :",
    emailPlaceholder: "ईमेल दर्ज करें",
    candidateContactTitle: "उम्मीदवार संपर्क :",
    familyMemberContactTitle: "परिवार सदस्य संपर्क",
    contactGuideInfoText:
      "ऊपर दिया गया संपर्क नंबर बायोडाटा में संपर्क के रूप में प्रदान किया जाएगा।",
    // occupation table
    Engineer: "इंजीनियर",
    Doctor: "डॉक्टर",
    Driver: "चालक",
    Teacher: "शिक्षक",
    Lawyer: "वकील",
    Nurse: "नर्स",
    Architect: "वास्तुकार",
    Electrician: "बिजली मिस्त्री",
    Plumber: "प्लंबर",
    Carpenter: "बढ़ई",
    Chef: "शेफ",
    Pilot: "पायलट",
    Artist: "कलाकार",
    Farmer: "किसान",
    Mechanic: "मेकैनिक",
    Scientist: "वैज्ञानिक",
    Pharmacist: "फार्मासिस्ट",
    SoftwareDeveloper: "सॉफ्टवेयर डेवलपर",
    Accountant: "लेखाकार",
    PoliceOfficer: "पुलिस अधिकारी",
    Other: "अन्य",
    //caste dropdown
    TokareKoli: "टोकरे कोळी",
    MahadevKoli: "महादेव कोळी",
    DhorKoli: "ढोर कोळी",
    Koli: "कोळी",
    // Other: "इतर",

    tenth: "१०वीं",
    twelvth: "१२वीं",
    Engineering: "इंजीनियरिंग",
    BachelorDegree: "स्नातक डिग्री",
    MasterDegree: "स्नातकोत्तर डिग्री",
    PhD: "पीएच.डी.",
    Diploma: "डिप्लोमा",
    Certificate: "प्रमाणपत्र",
    AssociateDegree: "सहायक डिग्री",
    VocationalTraining: "व्यावसायिक प्रशिक्षण",
    ProfessionalQualification: "व्यावसायिक योग्यता",
    // Other: "अन्य"
    DontKnow: "पता नहीं",
    Yes: "हां",
    No: "नहीं",
    District: "जिल्हा",
    Subdistrict: "तालुका",
    Village: "गाव",
    Maharashtra: "महाराष्ट्र",
    Search: "खोजें...",
    timeOfDayMorningHindi: "सुबह",
    timeOfDayAfternoonHindi: "दोपहर",
    timeOfDayEveningHindi: "शाम",
    timeOfDayNightHindi: "रात",
    //actual biodata pic
    overview: "समीक्षा",
    vaivahikStiti: "वैवाहिक स्थिति",
    vyavsay: "व्यवसाय",
    raktgat: "रक्त समूह",
    gav: "गाँव",
    taluka: "तहसील",
    jilha: "जिला",
    mamacheGav: "मामा का गांव",
    apangatva: "विकलांगता",
    janmakundaliMahiti: "जन्म कुंडली जानकारी",
    janmasthan: "जन्म स्थान",
    biodata: "बायोडाटा",
    vaiyaktikMahiti: "व्यक्तिगत जानकारी",
    sampurnaNav: "पूरा नाम",
    janmatarih: "जन्म तिथि",
    vay: "उम्र",
    varn: "वर्ण",
    jat: "जाति",
    unchi: "ऊँचाई",
    shaikshanikMahiti: "शैक्षिक जानकारी",
    nokriVyavsay: "नौकरी व्यवसाय",
    varshikUtpan: "वार्षिक आय",
    nokricheThikan: "नौकरी का स्थान",
    kautumbikParshwabhumiTapsil: "पारिवारिक पृष्ठभूमि विवरण",
    vadilNav: "पिता का नाम",
    vadilVyavsay: "पिता का व्यवसाय",
    aicheNav: "माता का नाम",
    ekunBhav: "कुल भाई",
    vivahitBhav: "विवाहित भाई",
    ekunBahin: "कुल बहनें",
    vivahitBahin: "विवाहित बहनें",
    mamacheSampurnaNav: "मामा का पूरा नाम",
    // mamacheGav: "मामा का गांव",
    samparkachiMahiti: "संपर्क जानकारी",
    samparkKramank: "संपर्क नंबर",
    kaimchaPatta: "स्थाई पता",
    apeksha: "अपेक्षा",
    koniVisheshApekshaNahi: "कोई विशेष अपेक्षा नहीं",
    adhikMahitiSathi: "अधिक जानकारी के लिए",
    haIdMobileAppSearch:
      "इस आईडी को मोबाइल ऐप में खोजें और अधिक जानकारी और फोटो देखें",
    janma: "जन्म",
    //biodataTemplate
    submitBtn: "जमा करें",
    noTemplateSelected: "कोई टेम्पलेट नहीं चुना गया",
    noImageAvailable: "कोई छवि उपलब्ध नहीं है",
    chooseTemplate: "टेम्पलेट चुनें",

    selectCandidateType: "कृपया उम्मीदवार का प्रकार चुनें.",
    // enterName: "कृपया नाम दर्ज करें.",
    enterMiddleName: "कृपया मध्य नाम दर्ज करें.",
    enterSurname: "कृपया उपनाम दर्ज करें.",
    ageRequirement: "उम्मीदवार की उम्र १८ वर्ष होनी चाहिए.",
    chooseMaritalStatus: "कृपया वैवाहिक स्थिति चुनें.",
    chooseComplexion: "कृपया वैध रंग चुनें.",
    selectPhoto: "कृपया एल्बम में फोटो चुनें.",
    minimumPhotos: "कृपया एल्बम में कम से कम २ फोटो चुनें.",
    chooseCaste: "कृपया वैध जाति चुनें.",
    choosePhysicalStatus:
      "कृपया उम्मीदवार शारीरिक रूप से अक्षम है या नहीं चुनें.",
    chooseHeightFeet: "कृपया वैध ऊंचाई फीट में चुनें.",
    chooseHeightInch: "कृपया वैध ऊंचाई इंच में चुनें.",
    chooseBirthDistrict: "कृपया वैध जिला चुनें.",
    chooseBirthSubDistrict: "कृपया वैध उप-जिला चुनें.",
    chooseBirthVillage: "कृपया वैध गांव चुनें.",
    chooseBirthTime: "कृपया वैध जन्म समय चुनें या फिर से चुनें.",
    chooseQualification: "कृपया वैध योग्यता चुनें.",
    chooseOccupation: "कृपया वैध व्यवसाय चुनें.",
    chooseIncome: "कृपया वैध वार्षिक आय श्रेणी चुनें.",
    chooseWorkDistrict: "कृपया वैध जिला चुनें.",
    chooseWorkSubDistrict: "कृपया वैध उप-जिला चुनें.",
    chooseWorkVillage: "कृपया वैध गांव चुनें.",
    enterFatherName: "कृपया पिता का नाम दर्ज करें.",
    enterMotherName: "कृपया माँ का नाम दर्ज करें.",
    enterMaternalUncleName: "कृपया मामा का नाम दर्ज करें.",
    chooseMaternalDistrict: "कृपया वैध जिला चुनें.",
    chooseMaternalSubDistrict: "कृपया वैध उप-जिला चुनें.",
    chooseMaternalVillage: "कृपया वैध गांव चुनें.",
    chooseLocationDistrict: "कृपया वैध जिला चुनें.",
    chooseLocationSubDistrict: "कृपया वैध उप-जिला चुनें.",
    chooseLocationVillage: "कृपया वैध गांव चुनें.",
    enterCandidateMobile: "कृपया वैध मोबाइल नंबर दर्ज करें.",
    enterFamilyMobile: "कृपया वैध मोबाइल नंबर दर्ज करें.",
  },
  mr: {
    call: "संपर्क करा",

    alertMessage: "कृपया योग्य माहिती भरा",
    continue: "पुढे जा",
    register: "नोंदणी करा",
    password: "पासवर्ड",
    login: "लॉगिन",
    Business: "व्यवसाय",

    enterMobileNumber: "कृपया मोबाईल नंबर प्रविष्ट करा",
    enterName: "कृपया नाव प्रविष्ट करा",
    enterPassword: "कृपया पासवर्ड प्रविष्ट करा",
    invalidPassword: "कृपया किमान 8 अक्षरांचा वैध पासवर्ड प्रविष्ट करा",
    Unemployed: "बेरोजगार",

    home: "मुख्य पान",
    profile: "प्रोफाइल",
    findPeople: "लोक शोधा",
    notifications: "सूचना",
    settings: "सेटिंग्ज",
    meetingCalender: "बैठक कैलेंडर",
    bookmarkItem: "सेव्ह केलेली यादी",
    createBiodata: "बायोडाटा तयार करा",
    chooseBiodataDesign: "बायोडाटा डिझाईन निवडा",
    signUp: "साइन अप करा",
    explore: "शोधा",
    welcome: "सुस्वागतम 🙏",
    profileCreatedListHeadingHomePage: "तयार केलेले बायोडाटा",
    verifiedTextHomePage: "पडताळणी",
    name: "नाव",
    age: "वय",
    occupation: "व्यवसाय",
    location: "स्थान",
    firstName: "पहिले नाव",
    middleName: "वडिलांचे नाव",
    surname: "आडनाव",
    qualification: "पात्रता",
    noAlbumWarning: "अल्बम उपलब्ध नाही",
    album: "अल्बम",
    albumPrivateText: "हा अल्बम खाजगी आहे",
    requestAlbumPermission: "अल्बम पाहण्यासाठी विनंती करा",
    personalInfoPrivateText: "वैयक्तिक माहिती खाजगी आहे",
    requestForPersonalInformation: "वैयक्तिक माहिती पाहण्याची विनंती करा",
    familyInfoPrivateText: "कौटुंबिक माहिती खाजगी आहे",
    requestForfamilyInformation: "कौटुंबिक माहिती पाहण्याची विनंती करा",
    homeAddressInfoPrivateText: "घराचा पत्ता खाजगी आहे",
    requestForHomeAddress: "घराचा पत्ता पाहण्याची करण्याची विनंती",
    direction: "पत्ता पहा",
    mobileNumberInfoPrivateText: "संपर्क क्रमांक खाजगी आहे",
    requestForMobileNumber: "मोबाईल नंबर पाहण्याची विनंती",
    contact: "संपर्क करा",
    private: "खाजगी",
    sendIntrest: "इच्छा दर्शवा",
    viewProfile: "प्रोफाइल पहा",
    goBack: "मागे",
    goNext: "पुढील पान",
    // Onboarding Screen
    imCandidate: "मी अर्जदार आहे",
    imKolidut: "मी कोळीदूत आहे",
    imRelativeOfCandidate: "मी अर्जदाराचा नातेवाईक आहे",
    tellUsAboutYourSelf: "कृपया तुमचा परिचय द्या",
    tellusSubText: "कृपया स्वतःबद्दल वर्णन करणारा पर्याय निवडा",
    selectRelation: "आपले नाते निवडा",
    selectRelationSubText:
      "कृपया असा पर्याय निवडा जो अर्जदाराशी आपल्या नात्याचे वर्णन करतो",
    selectOptionSubText: "कृपया पर्याय निवडा",

    father: "वडील",
    mother: "आई",
    other: "इतर",
    male: "पुरुष",
    female: "महिला",
    mobileNumber: "मोबाइल नंबर",
    mobileNumberSubText: "कृपया आपला संपर्क क्रमांक नोंदवा",
    selectOption: "खालील पर्याय निवडा",

    //Side Drawer
    timeline: "माझा प्रवास",

    //BioData
    feet: "फूट",
    inch: "इंच",
    candidateTypeMale: "वर",
    candidateTypeFemale: "वधू",
    expectationSectionTitle: "वधूकडून / वराकडून अपेक्षा",
    biodataTitle: "बायोडाटा तयार करा",
    submit: "अर्ज सादर करा",
    basicDetailTitle: "मूलभूत माहिती तपशील",
    candidateType: "उमेदवार प्रकार:",
    selectCandidateTypePlaceHolder: "उमेदवाराचा प्रकार निवडा",
    nameTitle: "नाव :",
    namePlaceholder: "तुमचं नाव टाका",
    middleNameTitle: "मधलं नाव:",
    middleNamePlaceHolder: "तुमचं मधलं नाव टाका",
    surnameTitle: "आडनाव :",
    surnamePlaceHolder: "तुमचं आडनाव टाका",
    fullNameTitle: "पूर्ण नाव:",
    dob: "जन्मतारीख:",
    ageTitle: "वय:",
    maritalStatusTitle: "वैवाहिक स्थिती:",
    maritalStatusPlaceholder: "वैवाहिक स्थिती निवडा",
    complexion: "वर्ण :",
    complexionPlaceholder: "वर्ण निवडा ",
    //Martitial Status Dropdown
    single: "अविवाहित",
    married: "विवाहित",
    divorced: "घटस्फोटित",
    widowed: "विधवा",
    //Complexion Dropdown
    very_fair: "अतिशय गोरा",
    fair: "गोरा",
    light: "हलका गोरा",
    medium: "मध्यम गोरा",
    olive: "जैतून",
    tan: "मध्यम तपकिरी",
    brown: "तपकिरी",
    dark: "काळा",
    //album section
    addImageTitle: "फोटो निवडा",
    profilePicture: "मुख्य फोटो",
    useAsProfilePicture: "मुख्य फोटोसाठी निवडा",
    albumGuideText:
      "निळ्या बटणावर क्लिक करून तुम्ही दुसरे फोटो प्रोफाइल चित्र म्हणून निवडू शकता",
    personalInfoHeading: "वैयक्तिक माहिती",
    casteTitle: "जात :",
    castPlaceHolder: "तुमची जात निवडा",
    bloodGroupTitle: "रक्तगट :",
    bloodGroupPlaceHolder: "रक्तगट निवडा",
    physicalDisabledTitle: "शारीरिक अपंगत्व :",
    physicalDisablePlaceholder: "तुम्ही शारीरिकदृष्ट्या अपंग आहात का?",
    heightTitle: "उंची :",
    feetPlaceholder: "फूट",
    inchPlaceholder: "इंच",
    birthPlaceTitle: "जन्म स्थान :",
    birthTimeTitle: "जन्म वेळ :",
    timePlaceholder: "वेळ",
    hourPlaceholder: "तास",
    minutePlaceholder: "मिनिट",
    qualificationTitle: "अर्हता :",
    qualificationPlaceholder: "तुमची अर्हता निवडा",
    occupationTitle: "व्यवसाय :",
    occupationPlaceholder: "तुमचा व्यवसाय निवडा",
    occupationMoreInfoTitle: "व्यवसायाची अधिक माहिती :",
    occupationMoreinfoPlaceholder: "अधिक माहिती भरा",
    yearlyincomeTitle: "वार्षिक उत्पन्न :",
    yearlyincomePlaceholder: "तुमची उत्पन्न श्रेणी निवडा",
    candidateWorkPlaceTitle: "व्यवसायाचे ठिकाण :",
    //कौटुंबिक info
    familyInfoTitle: "कौटुंबिक माहिती तपशील",
    fatherNameTitle: "वडिलांचे पूर्ण नाव :",
    fatherNamePlaceholder: "वडिलांचे नाव भरा",
    fatherOccupationTitle: "वडिलांचा व्यवसाय :",
    fatherOccupationPlaceholder: "वडिलांचा व्यवसाय भरा",
    motherNameTitle: "आईचे पूर्ण नाव :",
    motherNamePlaceholder: "आईचे नाव भरा",
    totalBrotherTitle: "एकूण भाऊ :",
    totalSisterTitle: "एकूण बहिणी :",
    totalMarriedBrotherTitle: "एकूण विवाहित भाऊ :",
    totalMarriedSisterTitle: "एकूण विवाहित बहिणी :",
    maternalUncleTitle: "मामाचे पूर्ण नाव :",
    maternalUnclePlaceHolder: "पहिले नाव मधले नाव आडनाव",
    maternalUnclePlace: "मामाचे गाव :",
    //expecttationSection
    expectationsTitle: "अपेक्षा :",
    expectationsPlaceholder: "३ अपेक्षा निवडा",
    expectationGuideText:
      "तुमच्या कोणत्याही अपेक्षा नसल्यास ते रिकामे ठेवू शकता.",
    expectationAlertText: "तुम्ही जास्तीत जास्त ३ अपेक्षा निवडू शकता.",
    expectationAlertTitle: "मर्यादा गाठली",
    //LocationSection
    loacationInfoTitle: "स्थानाची माहिती",
    permanantAddresstitle: "कायमचा पत्ता :",
    //contactInfoSection
    contactInfoTitle: "संपर्क माहिती",
    emailTitle: "ईमेल :",
    emailPlaceholder: "ईमेल भरा",
    candidateContactTitle: "उमेदवार संपर्क :",
    familyMemberContactTitle: "कुटुंबातील सदस्यांचा संपर्क :",
    contactGuideInfoText:
      "वरील संपर्क क्रमांक बायोडेटावर संपर्क म्हणून प्रदान दिला जाईल.",
    // Occupation Table
    Engineer: "इंजिनिअर",
    Doctor: "डॉक्टर",
    Driver: "चालक",
    Teacher: "शिक्षक",
    Lawyer: "वकील",
    Nurse: "नर्स",
    Architect: "वास्तुविशारद",
    Electrician: "विद्युत तंत्रज्ञ",
    Plumber: "प्लंबर",
    Carpenter: "सुतार",
    Chef: "खानसामा",
    Pilot: "वैमानिक",
    Artist: "कलाकार",
    Farmer: "शेतकरी",
    Mechanic: "मेकॅनिक",
    Scientist: "शास्त्रज्ञ",
    Pharmacist: "फार्मासिस्ट",
    SoftwareDeveloper: "सॉफ्टवेअर डेवलपर",
    Accountant: "लेखापाल",
    PoliceOfficer: "पोलीस अधिकारी",
    Other: "इतर",
    //caste dropdown
    TokareKoli: "टोकरे कोळी",
    MahadevKoli: "महादेव कोळी",
    DhorKoli: "ढोर कोळी",
    Koli: "कोळी",
    // Other: "इतर",
    tenth: "१० वी",
    twelvth: "१२ वी",
    Engineering: "अभियांत्रिकी",
    BachelorDegree: "स्नातक पदवी",
    MasterDegree: "स्नातकोत्तर पदवी",
    PhD: "पीएच.डी.",
    Diploma: "डिप्लोमा",
    Certificate: "प्रमाणपत्र",
    AssociateDegree: "सहाय्यक पदवी",
    VocationalTraining: "व्यावसायिक प्रशिक्षण",
    ProfessionalQualification: "व्यावसायिक पात्रता",
    // Other: "इतर"
    DontKnow: "माहित नाही",
    Yes: "होय",
    No: "नाही",

    District: "जिल्हा",
    Subdistrict: "तालुका",
    Village: "गाव",
    Maharashtra: "महाराष्ट्र",
    Search: "शोधा...",
    timeOfDayMorning: "सकाळी",
    timeOfDayAfternoon: "दुपारी",
    timeOfDayEvening: "संध्याकाळी",
    timeOfDayNight: "रात्री",
    //actaul biodata pic
    overview: "आढावा",
    vaivahikStiti: "वैवाहिक स्थिती",
    vyavsay: "व्यवसाय",
    raktgat: "रक्तगट",
    gav: "गाव",
    taluka: "तालुका",
    jilha: "जिल्हा",
    mamacheGav: "मामाचे गाव",
    apangatva: "अपंगत्व",
    janmakundaliMahiti: "जन्मकुंडली माहिती",
    janmasthan: "जन्मस्थान",
    biodata: "बायोडाटा",
    vaiyaktikMahiti: "वैयक्तिक माहिती",
    sampurnaNav: "संपूर्ण नाव",
    janmatarih: "जन्मतारीख",
    vay: "वय",
    varn: "वर्ण",
    jat: "जात",
    unchi: "उंची",
    shaikshanikMahiti: "शैक्षणिक माहिती",
    nokriVyavsay: "नोकरी व्यवसाय",
    varshikUtpan: "वार्षिक उत्पन्न",
    nokricheThikan: "नोकरीचे ठिकाण",
    kautumbikParshwabhumiTapsil: "कौटुंबिक पार्श्वभूमी तपशील",
    vadilNav: "वडील नाव",
    vadilVyavsay: "वडील व्यवसाय",
    aicheNav: "आईचे नाव",
    ekunBhav: "एकूण भाऊ",
    vivahitBhav: "विवाहित भाऊ",
    ekunBahin: "एकूण बहिणी",
    vivahitBahin: "विवाहित बहिणी",
    mamacheSampurnaNav: "मामाचे संपूर्ण नाव",
    // mamacheGav: "मामाचे गाव",
    samparkachiMahiti: "संपर्काची माहिती",
    samparkKramank: "संपर्क क्रमांक",
    kaimchaPatta: "कायमचा पत्ता",
    apeksha: "अपेक्षा",
    koniVisheshApekshaNahi: "कोणत्याही विशेष अपेक्षा नाहीत",
    adhikMahitiSathi: "अधिक माहिती साठी",
    haIdMobileAppSearch:
      "हा आयडी मोबाईल अँप मध्ये शोधून अधिक माहिती व फोटो पहा",
    janma: "जन्म",
    //biodata template
    submitBtn: "सबमिट करा",
    noTemplateSelected: "कोणताही टेम्पलेट निवडलेला नाही",
    noImageAvailable: "कोणतीही छायाचित्रे उपलब्ध नाहीत",
    chooseTemplate: "डिझाइन निवडा",

    selectCandidateType: "कृपया उमेदवाराचा प्रकार निवडा.",
    // enterName: "कृपया नाव प्रविष्ट करा.",
    enterMiddleName: "कृपया मधले नाव प्रविष्ट करा.",
    enterSurname: "कृपया आडनाव प्रविष्ट करा.",
    ageRequirement: "उमेदवाराचे वय १८ वर्ष असावे.",
    chooseMaritalStatus: "कृपया वैवाहिक स्थिती निवडा.",
    chooseComplexion: "कृपया वैध रंग निवडा.",
    selectPhoto: "कृपया अल्बममधील फोटो निवडा.",
    minimumPhotos: "कृपया अल्बममधील किमान २ फोटो निवडा.",
    chooseCaste: "कृपया वैध जात निवडा.",
    choosePhysicalStatus: "कृपया उमेदवार शारीरिकदृष्ट्या अपंग आहे का ते निवडा.",
    chooseHeightFeet: "कृपया वैध उंची फूट मध्ये निवडा.",
    chooseHeightInch: "कृपया वैध उंची इंच मध्ये निवडा.",
    chooseBirthDistrict: "कृपया वैध जिल्हा निवडा.",
    chooseBirthSubDistrict: "कृपया वैध तालुका निवडा.",
    chooseBirthVillage: "कृपया वैध गाव निवडा.",
    chooseBirthTime: "कृपया वैध जन्म वेळ निवडा किंवा पुन्हा निवडा.",
    chooseQualification: "कृपया वैध शैक्षणिक पात्रता निवडा.",
    chooseOccupation: "कृपया वैध व्यवसाय निवडा.",
    chooseIncome: "कृपया वैध वार्षिक उत्पन्न श्रेणी निवडा.",
    chooseWorkDistrict: "कृपया वैध जिल्हा निवडा.",
    chooseWorkSubDistrict: "कृपया वैध तालुका निवडा.",
    chooseWorkVillage: "कृपया वैध गाव निवडा.",
    enterFatherName: "कृपया वडिलांचे नाव प्रविष्ट करा.",
    enterMotherName: "कृपया आईचे नाव प्रविष्ट करा.",
    enterMaternalUncleName: "कृपया मावशीचे नाव प्रविष्ट करा.",
    chooseMaternalDistrict: "कृपया वैध जिल्हा निवडा.",
    chooseMaternalSubDistrict: "कृपया वैध तालुका निवडा.",
    chooseMaternalVillage: "कृपया वैध गाव निवडा.",
    chooseLocationDistrict: "कृपया वैध जिल्हा निवडा.",
    chooseLocationSubDistrict: "कृपया वैध तालुका निवडा.",
    chooseLocationVillage: "कृपया वैध गाव निवडा.",
    enterCandidateMobile: "कृपया वैध मोबाइल नंबर प्रविष्ट करा.",
    enterFamilyMobile: "कृपया वैध मोबाइल नंबर प्रविष्ट करा.",
  },
};

export default TRANSLATIONS;
